<a href="https://colab.research.google.com/github/Fidhavk/Machine-Learning-project/blob/main/ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
data = pd.read_csv('/content/student_habits_performance.csv')

In [ ]:
data

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [ ]:
data.shape

(1000, 16)

In [ ]:

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   object
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   object
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   object
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   object
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    object
 12  internet_quality               1000 non-null   object
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   object
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), object(7)
memory usage: 125.1+ KB

In [ ]:
data.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [ ]:
data['parental_education_level']=data['parental_education_level'].fillna('No')

data['parental_education_level']=data['parental_education_level'].replace({
    'None' : 'No',
    'Bachelor':'Yes',
    'Master':'Yes',
    'High School':'Yes'
})
data['parental_education_level']= data['parental_education_level'].map({'No':0,'Yes':1})

In [ ]:
data.isnull().sum()

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [ ]:
data['parental_education_level'].value_counts()

parental_education_level
1    909
0     91
Name: count, dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day',
       'social_media_hours', 'netflix_hours', 'part_time_job',
       'attendance_percentage', 'sleep_hours', 'diet_quality',
       'exercise_frequency', 'parental_education_level', 'internet_quality',
       'mental_health_rating', 'extracurricular_participation', 'exam_score'],
      dtype='object')

In [ ]:
data.drop('student_id',axis=1,inplace=True)

In [ ]:
le = LabelEncoder()
data['gender']=le.fit_transform(data['gender'])
data['part_time_job']=le.fit_transform(data['part_time_job'])
data['diet_quality']=le.fit_transform(data['diet_quality'])
data['parental_education_level']=le.fit_transform(data['parental_education_level'])
data['internet_quality']=le.fit_transform(data['internet_quality'])
data['extracurricular_participation']=le.fit_transform(data['extracurricular_participation'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1000 non-null   int64
 1   gender                         1000 non-null   int64
 2   study_hours_per_day            1000 non-null   float64
 3   social_media_hours             1000 non-null   float64
 4   netflix_hours                  1000 non-null   float64
 5   part_time_job                  1000 non-null   int64
 6   attendance_percentage          1000 non-null   float64
 7   sleep_hours                    1000 non-null   float64
 8   diet_quality                   1000 non-null   int64
 9   exercise_frequency             1000 non-null   int64
 10  parental_education_level       1000 non-null   int64
 11  internet_quality               1000 non-null   int64
 12  mental_health_rating           1000 non-null   int64
 13  extracurricular_participation  1000 non-null   int64
 14  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(9)
memory usage: 117.3 KB

In [ ]:
x = data.drop('exam_score',axis=1)
y = data['exam_score']

In [ ]:
x

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation
0,23,0,0.0,1.2,1.1,0,85.0,8.0,0,6,1,0,8,1
1,20,0,6.9,2.8,2.3,0,97.3,4.6,1,6,1,0,8,0
2,21,1,1.4,3.1,1.3,0,94.8,8.0,2,1,1,2,1,0
3,23,0,1.0,3.9,1.0,0,71.0,9.2,2,4,1,1,1,1
4,19,0,5.0,4.4,0.5,0,90.9,4.9,0,3,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,0,2.6,0.5,1.6,0,77.0,7.5,0,2,1,1,6,1
996,17,0,2.9,1.0,2.4,1,86.0,6.8,2,1,1,0,6,1
997,20,1,3.0,2.6,1.3,0,61.9,6.5,1,5,1,1,9,1
998,24,1,5.4,4.1,1.1,1,100.0,7.6,0,0,1,0,1,0
999,19,0,4.3,2.9,1.9,0,89.4,7.1,1,2,1,0,8,0

In [ ]:
y

0       56.2
1      100.0
2       34.3
3       26.8
4       66.4
       ...
995     76.1
996     65.9
997     64.4
998     69.7
999     74.9
Name: exam_score, Length: 1000, dtype: float64

#Linear Regression

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=30)

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
pd.DataFrame({
    'actual': y_test,
   ' predict':y_pred
})

     actual    predict
923    53.4  56.012426
921    85.4  76.733212
516    80.9  83.868380
87     47.2  51.738884
879    44.3  46.950445
..      ...        ...
711    70.9  69.169679
517   100.0  98.847877
984    82.4  79.159143
886    65.6  55.193011
961    81.1  88.951505

[200 rows x 2 columns]

In [ ]:
model.score(x_train,y_train)*100

89.46596342902147

In [ ]:
model.score(x_test,y_test)*100

92.29592293679286

In [ ]:
mean_absolute_error(y_test,y_pred)

3.9512251637063134

In [ ]:
mean_squared_error(y_test,y_pred)

24.468501426133642

In [ ]:

r2_score(y_test,y_pred)*100

92.29592293679286

#Svm

In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:

x_train,x_test,y_train,y_test = train_test_split (x,y,test_size=0.20,random_state=25)

In [ ]:
model = SVR()
model.fit(x_train,y_train)

SVR()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
mean_absolute_error(y_test,y_pred)

12.579464299539417

In [ ]:
mean_squared_error(y_test,y_pred)

241.8918967800996

In [ ]:
r2_score(y_test,y_pred)*100

6.65298294790897

#Descion Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=45)

In [ ]:
model = DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [ ]:
y_pred= model.predict(x_test)

In [ ]:
mean_absolute_error(y_test,y_pred)

7.076000000000001

In [ ]:
mean_squared_error(y_test,y_pred)

77.8893

In [ ]:

r2_score(y_test,y_pred)

0.7436115530215608

#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = RandomForestRegressor(n_estimators=53,max_depth=8,random_state=25)
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=8, n_estimators=53, random_state=25)

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
mean_absolute_error(y_test,y_pred)

5.3290861031749

In [ ]:
mean_squared_error(y_test,y_pred)

43.16808505519341

In [ ]:
r2_score(y_test,y_pred)

0.8579034824252598

#KNN

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.20, random_state=25)

In [ ]:
model = KNeighborsRegressor()
model.fit(x_train,y_train)

KNeighborsRegressor()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)

0.6086850407824793